CREATE TABLE decora_products (
   id Serial,
   ean Varchar(32),
   vendor Varchar(16),
   product Varchar(64),
   collection Varchar(64),
   sap Varchar(32),
   color Varchar(16),
   structure Varchar(32),
   source Varchar(64),
   pl Integer Default 1,
   en Integer Default 1,
   de Integer Default 1,
   ru Integer Default 1,
   name_pl Text,
   name_en Text,
   name_de Text,
   name_ru Text,
   name_www_pl Text,
   name_www_en Text,
   name_www_de Text,
   name_www_ru Text,
   desc_pl Text,
   desc_en Text,
   desc_de Text,
   desc_ru Text,
   desc_short_pl Text,
   desc_short_en Text,
   desc_short_de Text,
   desc_short_ru Text,
   dimension Varchar(32),
   pieces Integer,
   set_quantity Double precision,
   price_pl Double precision,
   price_en Double precision,
   price_de Double precision,
   price_ru Double precision,
   features Text,
   access Varchar(32),
   assembly Varchar(32)
   
);

CREATE UNIQUE INDEX decora_products_key ON decora_products (ean,vendor);
CREATE INDEX decora_products_key2 ON decora_products (vendor,product,collection);
